### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Hello526** [cedrickchee/ssd-yolo-retinanet#1]
Does the "50%mAP on VOC2007" you mentioned in TODO refer to YOLOV3?

**Comment by cedrickchee** [comment]
RetinaNet. I have not report results for YOLO yet. It's in my TODO.

**Comment by Hello526** [comment]
Thank you very much! Looking forward to your research.





--

祝您工作顺利！
李玙乾（硕士研究生） 
清华大学机械系
地址：广东省深圳市南山区西丽大学城能源环境大楼911B室
邮编：518055
TEL：15625206501
——————————————————————————


Thank you for your kind attention!

Li YuQian (Master graduate)

Department of Mechanical Engineering , Tsinghua University

Address: Room 911B, Energy and Environment Building, Xili University Town, Nanshan District, Shenzhen

Zip code : 518055

Tel : 15625206501

At 2018-11-07 23:46:57, "Cedric Chee" <notifications@github.com> wrote:


RetinaNet. I have not report results for YOLO yet. It's in my TODO.
